"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

import math 

def fib(n):
    phi = (1 + math.sqrt(5)) / 2
    return round(pow(phi, n) / math.sqrt(5))

maxTerms = 4000000

n = 0
fibValue = fib(n)
evenSeq = []
while(fibValue < maxTerms):
    n=n+1
    if(fibValue % 2 == 0):
        evenSeq.append(fibValue)
    fibValue = fib(n)

print(sum(evenSeq))